[build-system]
requires = [ "setuptools>=40.6.0", "wheel>=0.34.2",]
build-backend = "setuptools.build_meta"

[tool.importcheck]
always = [ "flake8_prettycount", "flake8_prettycount.__main__", "flake8_prettycount.application",]
